name: Pull Request

on:
  pull_request:
    branches:
      - master
  #push:
  #  branches:
  #    - gh_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello world!"